[project]
name = "re-builder"
version = "0.0.2"
description = "Build GitHub Actions Runner images locally"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lark>=1.2.2",
    "notebook>=7.3.2",
    "python-hcl2>=6.1.1",
]
